spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: admin

    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt-secret: 63a3101ac990aa2382bc6233189c036035fff09b46f0e18834614273e252debd
  jwt-expiration-time: 86400000

